### ISSUE TITLE
Is it possible to delete the created SplitType instance? 

### ISSUE THREAD

**Issue by allkrain** [lukePeavey/SplitType#39] opened 2022-06-29 04:48 UTC
Is it possible to correctly remove an existing SplitType instance when, for example, unmounting a vue component? Otherwise, if I unmount using revert on the next connections for the first time, I get no text split at all, and then I get a double split. Each letter is perceived as a separate word and turns into two additional elements `.word` and `.char`

**Comment by lukePeavey** [comment] 2022-06-30 22:28
Would it be possible to provide a live example of this issue on codeSandbox?

**Comment by lukePeavey** [comment] 2022-07-01 02:37
Try it without calling revert on Unmount

**Comment by lukePeavey** [comment] 2022-07-02 06:27
> Is it possible to correctly remove an existing SplitType instance when, for example, unmounting a vue component?

To answer the first part of your question, calling the `revert` method is the correct way to cleanup a SplitType instance before the component is unmounted.  I created several simple examples using React and Vue, and was not able to reproduce the issue you described.  If you could provide a live example of this issue on CodeSandbox I will definitely check it out. 

### Vue

Use the `beforeUnmount` lifecycle method to perform cleanup. 

[Live Example on CodeSandbox](https://codesandbox.io/s/splittype-issue-39-vue-o7cy2h?file=/src/main.js)

```js
export default {
  name: 'SplitText',
  props: {
    msg: String,
  },
  // Split text and animate into view
  mounted() {
    this.text = SplitType.create('h1')
    this.animation = gsap.timeline()
    this.animation.from(this.text.chars, {
      y: 10,
      z: -50,
      scale: 0.5,
      opacity: 0,
      rotateX: 30,
      duration: 0.6,
      ease: 'back.out(2.0)',
      stagger: { each: 0.02 },
    })
  },
  // Cleanup:  kill animation and revert split text
  beforeUnmount() {
    this.animation.kill()
    this.text.revert()
  },
}
```

### React 

Use the cleanup function of an effect hook to revert text. 

[Live Example on CodeSandbox](https://codesandbox.io/s/splittype-issue-39-react-34qrge?file=/src/App.js)

```js
export default function Text({children}) {
  const target = useRef();
  useEffect(() => {
    if (target.current) {
      console.log("Splitting Text");

      // Split text and animate into view
      const text = SplitType.create("h1", { types: "lines,chars" });
      const animation = gsap.timeline();
      gsap.set(target.current, { visibility: "visible" });
      animation.from(text.chars, {
        y: 10,
        z: -50,
        scale: 0.5,
        rotateX: 30,
        opacity: 0,
        duration: 0.6,
        ease: "back.out(2.0)",
        stagger: { each: 0.02 }
      });
      // Cleanup:  kill animation and revert split text
      return function cleanup() {
        animation.kill();
        text.revert();
      };
    }
  }, []);

  return <h1 ref={target}>{children}</h1>;
}
```

**Comment by lukePeavey** [comment] 2022-07-02 06:55
Possibly related to #40

**Comment by allkrain** [comment] 2022-07-02 07:47
I tried to reproduce this problem for you here: https://codesandbox.io/s/new-snow-2fbcdo 
When you follow the link and back, you will see that the gradient text disappears.

**Comment by lukePeavey** [comment] 2022-07-02 09:27
@allkrain thanks I'll take a look

**Comment by lukePeavey** [comment] 2022-07-10 01:57
@allkrain pet me know if that worked for you

**Comment by lukePeavey** [comment] 2022-10-29 00:57
Closing this as answered

**Closed by lukePeavey** 2022-10-29 00:57 UTC
Labels: :grey_question:  type: question
